FossilHuntMVC/Models/Credentials.cs
using System.ComponentModel.DataAnnotations;

namespace TabloidMVC.Models
{
    public class Credentials
    {
        [Required]
        [DataType(DataType.EmailAddress)]
        public string Email { get; set; }

        [Required]
        public string Username { get; set; }
    }
}

FossilHuntMVC/Models/ErrorViewModel.cs
using System;

namespace FossilHuntMVC.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

FossilHuntMVC/Models/Question.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace FossilHuntMVC.Models
{
    public class Question
    {

        public int Id { get; set; }

        [Required]
        public int userId { get; set; }

        [Required]
        public string question { get; set; }

        [Required]
        public int StateId { get; set; }


        public User user;
    }
}

FossilHuntMVC/Models/User.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace FossilHuntMVC.Models
{
    public class User
    {
        public int Id { get; set; }

        [Required]
        public string Username { get; set; }

        [Required]
        public string Email { get; set; }

        public string UserImage { get; set; }

    }
}

FossilHuntMVC/Controllers/AccountController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Security.Claims;
using System.Threading.Tasks;
using TabloidMVC.Models;
using TabloidMVC.Repositories;

namespace TabloidMVC.Controllers
{
    public class AccountController : Controller
    {
        private readonly IUserProfileRepository _userProfileRepository;

        public AccountController(IUserProfileRepository userProfileRepository)
        {
            _userProfileRepository = userProfileRepository;
        }

        public IActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Login(Credentials credentials)
        {
            var userProfile = _userProfileRepository.GetByEmail(credentials.Email, credentials.Username);

            if (userProfile == null)
            {
                ModelState.AddModelError("Email", "Invalid email or Username");
                return View();
            }

            var claims = new List<Claim>
            {
                new Claim(ClaimTypes.NameIdentifier, userProfile.Id.ToString()),
                new Claim(ClaimTypes.Email, userProfile.Email),
            };

            var claimsIdentity = new ClaimsIdentity(
                claims, CookieAuthenticationDefaults.AuthenticationScheme);

            await HttpContext.SignInAsync(
                CookieAuthenticationDefaults.AuthenticationScheme,
                new ClaimsPrincipal(claimsIdentity));

            return RedirectToAction("Index", "Home");
        }

        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync();
            return RedirectToAction("Index", "Home");
        }
    }
}

FossilHuntMVC/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using FossilHuntMVC.Models;

namespace FossilHuntMVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

FossilHuntMVC/Controllers/QuestionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using FossilHuntMVC.Repositories;
using Microsoft.AspNetCore.Mvc;

namespace FossilHuntMVC.Controllers
{
    public class QuestionController : Controller
    {
        private readonly IQuestionRepo _questionRepo;

        public QuestionController (IQuestionRepo questionRepo)
        {
            _questionRepo = questionRepo;
        }



        public IActionResult Index()
        {
            var questionList = _questionRepo.GetAll();
            return View(questionList);
        }
    }
}

FossilHuntMVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}


    <div class="container-fluid no-padding">
        <div class="row">
            <div class="col-md-12">
                <img class="col-lg-12" src="https://res.cloudinary.com/drcnakesm/image/upload/v1596567405/Ivory_and_Ash_Grey_Photo_DIY_Influencer_Minimalist_Facebook_Cover_zzshtx.png" alt="picture of a young man holding a fossil" />
            </div>
        </div>


        <div class="row">
            <div class="col-md-4">
                <img class="col-lg-12" src="https://res.cloudinary.com/drcnakesm/image/upload/v1600117448/CREATE_FOSSIL_HUNT_ACCOUNT_bmfrou.png" />
            </div>

            <div class="col-md-4">
                <img class="col-lg-12" src="https://res.cloudinary.com/drcnakesm/image/upload/v1600117453/Connect_with_other_fossil_hunters_using_The_Fossil_Hunt_forum_adwaiz.png" />
            </div>

            <div class="col-md-4">
                <img class="col-lg-12" src="https://res.cloudinary.com/drcnakesm/image/upload/v1600117457/UPLOAD_FOSSIL_FINS_TO_FOSSIL_COLLECTION_ACCOUNT_1_xqdnmb.png" />
            </div>
        </div>


      


    </div>
  
    
   

FossilHuntMVC/Views/Question/Index.cshtml
@model IEnumerable<FossilHuntMVC.Models.Question>

@{
    ViewData["Title"] = "Index";
}

<div class="container pt-5">

    <h1>Index</h1>

    <p>
        <a asp-action="Create">Create New</a>
    </p>
    <table class="table">
        <thead>
            <tr>
                
                <th>
                   Username
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.question)
                </th>
                
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {

            <tr>

                <td>
                    <a asp-action="Index">@Html.DisplayFor(modelItem => item.user.Username)</a>


                </td>
                <td>
                    @* need to add asp-route-id *@
                    <a asp-action="Index">@Html.DisplayFor(modelItem => item.question)</a>

                </td>
                <td>

                    @*  @Html.DisplayFor(modelItem => item.StateId)*@
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                    @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                    @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
                </td>
            </tr>
            }
        </tbody>
    </table>

</div>

FossilHuntMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - FossilHuntMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Fossil Hunt</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">

                        <li class="nav-item mx-0 mx-lg-1">
                            <a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" asp-area="" asp-controller="Home" asp-action="Index">HOME</a>
                        </li>

                        <li class="nav-item mx-0 mx-lg-1">
                            <a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" asp-area="" asp-controller="Question" asp-action="Index">Fossil Forum</a>
                        </li>

                       


                            <li class="nav-item mx-0 mx-lg-1">
                                <a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" asp-area="" asp-controller="Home" asp-action="Index">Collection</a>
                            </li>
                            <li class="nav-item mx-0 mx-lg-1">
                                <a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" asp-area="" asp-controller="Account" asp-action="Logout">Account</a>
                            </li>

                            <li class="nav-item mx-0 mx-lg-1">
                                <a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" asp-area="" asp-controller="Account" asp-action="Logout">LOGOUT</a>
                            </li>
                        
                            <li class="nav-item mx-0 mx-lg-1">
                                <a class="nav-link py-3 px-0 px-lg-3 rounded js-scroll-trigger" asp-area="" asp-controller="Account" asp-action="Login">LOGIN</a>
                            </li>
                        



                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div>
        <main role="main">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - FossilHuntMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>